# Generated by Django 4.2.30 on 2026-05-13 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_remove_doctorpayoutmethod_stripe_account_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, default='jazzcash', max_length=32)),
                ('amount_major', models.DecimalField(decimal_places=2, help_text='Charge amount in PKR (major units) for bookkeeping.', max_digits=14)),
                ('amount_minor', models.PositiveBigIntegerField(help_text='Amount sent to JazzCash (minor units, e.g. paisas).')),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('merchant_txn_ref', models.CharField(db_index=True, help_text='Merchant reference (pp_TxnRefNo).', max_length=64, unique=True)),
                ('gateway_txn_id', models.CharField(blank=True, help_text='Gateway reference when available (e.g. Retrieval / auth code composite).', max_length=128)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='initiated', max_length=20)),
                ('jazzcash_response_code', models.CharField(blank=True, max_length=16)),
                ('jazzcash_response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.appointment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GatewayTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound (to JazzCash)'), ('inbound', 'Inbound (return URL POST)')], max_length=16)),
                ('gateway', models.CharField(default='jazzcash', max_length=32)),
                ('raw_payload', models.JSONField(default=dict)),
                ('verified_hash', models.BooleanField(help_text='Null if hash not applicable.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_logs', to='accounts.appointment')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_logs', to='payments.payment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
