"""
Django settings for med_backend project.

Generated by 'django-admin startproject' using Django 4.2.17.
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config

from med_backend.py314_django_fix import apply as _apply_python314_django_fix

_apply_python314_django_fix()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne', ## for making live calls
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'rest_framework',
    'accounts',
    'payments',
    'medtag',
    'ai',
    #'rest_framework.authtoken',
    'corsheaders', # Required for CORS
    'channels', ## for making live calls 
    #'allauth',
    #'allauth.account',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <--- MOVED UP (Must be before CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- CORS SETTINGS (CRITICAL FOR FRONTEND CONNECTION) ---
CORS_ALLOW_ALL_ORIGINS = True # Allows both laptops to connect without IP issues

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH", # Required for Edit Profile
    "POST",
    "PUT",
]

# Allow standard headers (Authorization is key for JWT)
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


ROOT_URLCONF = 'med_backend.urls'
AUTH_USER_MODEL = 'accounts.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "my-app-auth",
    "JWT_AUTH_REFRESH_COOKIE": "my-refresh-token",
}

REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "accounts.serializers.UserSerializer"
}
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


WSGI_APPLICATION = 'med_backend.wsgi.application'

#for making live calls 
ASGI_APPLICATION = 'med_backend.asgi.application'
if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }



# Database (PostgreSQL via psycopg3 — works on Python 3.14+ where psycopg2 wheels may be unavailable)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=24),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- STRIPE SETTINGS ---
import stripe
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
stripe.api_key = STRIPE_SECRET_KEY

# Sandbox JazzCash/EasyPaisa (OTP-based; mirrors Stripe-style test flows)
# Disable in production unless you intentionally run integration tests against these endpoints.
def _truthy_setting(value):
    return str(value).strip().lower() in ('true', '1', 'yes', 'on')


WALLET_PAYMENT_SANDBOX = _truthy_setting(
    config('WALLET_PAYMENT_SANDBOX', default='True' if DEBUG else 'False')
)
WALLET_SANDBOX_OTP = config('WALLET_SANDBOX_OTP', default='4242')

# --- JazzCash (HTTP POST page redirect checkout) ---
# Put credentials ONLY in environment / .env (never commit real secrets).

PUBLIC_BASE_URL = config('PUBLIC_BASE_URL', default='http://127.0.0.1:8000')

JAZZCASH_TEST_MODE = _truthy_setting(
    config('JAZZCASH_TEST_MODE', default='True' if DEBUG else 'False')
)
JAZZCASH_MERCHANT_ID = config('JAZZCASH_MERCHANT_ID', default='').strip()
JAZZCASH_MERCHANT_PASSWORD = config('JAZZCASH_MERCHANT_PASSWORD', default='')
JAZZCASH_INTEGRITY_SALT = config('JAZZCASH_INTEGRITY_SALT', default='')

JAZZCASH_USD_TO_PKR_RATE = config('JAZZCASH_USD_TO_PKR_RATE', default='278.00')

JAZZCASH_SANDBOX_PAYMENT_POST_URL = config(
    'JAZZCASH_SANDBOX_PAYMENT_POST_URL',
    default='https://sandbox.jazzcash.com.pk/CustomerPortal/transactionmanagement/merchantform/',
)
JAZZCASH_PRODUCTION_PAYMENT_POST_URL = config(
    'JAZZCASH_PRODUCTION_PAYMENT_POST_URL',
    default='https://payments.jazzcash.com.pk/CustomerPortal/transactionmanagement/merchantform/',
)

JAZZCASH_PAY_SIGNING_SALT = config('JAZZCASH_PAY_SIGNING_SALT', default='medtag-jazzcash-pay')
try:
    JAZZCASH_PAY_LINK_MAX_AGE_SECONDS = int(config('JAZZCASH_PAY_LINK_MAX_AGE_SECONDS', default='3600'))
except ValueError:
    JAZZCASH_PAY_LINK_MAX_AGE_SECONDS = 3600

JAZZCASH_RESULT_FRONTEND_URL = config(
    'JAZZCASH_RESULT_FRONTEND_URL',
    default='',
)

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'cha84911@gmail.com'
EMAIL_HOST_PASSWORD = 'huts ctmz stcj tpfn'

# OTP Settings
OTP_EXPIRY_MINUTES = 10

REACTAPP_RESET_URL = config('REACTAPP_RESET_URL')
LOGIN_URI = config('LOGIN_URI')