"""
Django settings for med_backend project.

Generated by 'django-admin startproject' using Django 4.2.17.
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config

from med_backend.py314_django_fix import apply as _apply_python314_django_fix

_apply_python314_django_fix()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment
ENVIRONMENT = config('ENVIRONMENT', default='development')
IS_PRODUCTION = ENVIRONMENT == 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False').lower() in ('true', '1', 'yes')

# Properly configure allowed hosts for production
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'rest_framework',
    'accounts',
    'payments',
    'medtag',
    'ai',
    'corsheaders',
]

# Optional: Only use WebSocket features in development
if not IS_PRODUCTION:
    INSTALLED_APPS.extend([
        'channels',
    ])

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- CORS SETTINGS (PROPERLY CONFIGURED FOR PRODUCTION) ---
# In production, set specific frontend origins
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000').split(',')
if IS_PRODUCTION and '*' in CORS_ALLOWED_ORIGINS:
    # Security: Never allow all origins in production
    CORS_ALLOWED_ORIGINS = ['https://yourdomain.com']


ROOT_URLCONF = 'med_backend.urls'
AUTH_USER_MODEL = 'accounts.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "my-app-auth",
    "JWT_AUTH_REFRESH_COOKIE": "my-refresh-token",
}

REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "accounts.serializers.UserSerializer"
}
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


WSGI_APPLICATION = 'med_backend.wsgi.application'

# ASGI configuration (for WebSocket support in development only)
if not IS_PRODUCTION:
    ASGI_APPLICATION = 'med_backend.asgi.application'
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    # In production (Vercel), use standard WSGI
    ASGI_APPLICATION = 'med_backend.wsgi.application'
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }



# Database (PostgreSQL via psycopg3 — works on Python 3.14+ where psycopg2 wheels may be unavailable)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=24),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for production static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploads) - Use S3 in production, local storage in development
if IS_PRODUCTION:
    # AWS S3 Configuration for production
    USE_S3 = config('USE_S3', default='True').lower() in ('true', '1', 'yes')
    if USE_S3:
        # AWS settings
        AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
        AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
        AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
        AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-north-1')
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
        AWS_DEFAULT_ACL = 'public-read'
        AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
        
        # S3 static settings
        STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
        STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
        
        # S3 public media settings
        DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
        MEDIA_ROOT = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    else:
        # Fallback to local storage
        DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
        MEDIA_URL = '/media/'
        MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # Development: use local file storage
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- STRIPE SETTINGS ---
import stripe
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
stripe.api_key = STRIPE_SECRET_KEY

# Sandbox JazzCash/EasyPaisa (OTP-based; mirrors Stripe-style test flows)
# Disable in production unless you intentionally run integration tests against these endpoints.
def _truthy_setting(value):
    return str(value).strip().lower() in ('true', '1', 'yes', 'on')


WALLET_PAYMENT_SANDBOX = _truthy_setting(
    config('WALLET_PAYMENT_SANDBOX', default='True' if DEBUG else 'False')
)
WALLET_SANDBOX_OTP = config('WALLET_SANDBOX_OTP', default='4242')

# --- JazzCash (HTTP POST page redirect checkout) ---
# Put credentials ONLY in environment / .env (never commit real secrets).

PUBLIC_BASE_URL = config('PUBLIC_BASE_URL', default='http://127.0.0.1:8000')

JAZZCASH_TEST_MODE = _truthy_setting(
    config('JAZZCASH_TEST_MODE', default='True' if DEBUG else 'False')
)
JAZZCASH_MERCHANT_ID = config('JAZZCASH_MERCHANT_ID', default='').strip()
JAZZCASH_MERCHANT_PASSWORD = config('JAZZCASH_MERCHANT_PASSWORD', default='')
JAZZCASH_INTEGRITY_SALT = config('JAZZCASH_INTEGRITY_SALT', default='')

JAZZCASH_USD_TO_PKR_RATE = config('JAZZCASH_USD_TO_PKR_RATE', default='278.00')

JAZZCASH_SANDBOX_PAYMENT_POST_URL = config(
    'JAZZCASH_SANDBOX_PAYMENT_POST_URL',
    default='https://sandbox.jazzcash.com.pk/CustomerPortal/transactionmanagement/merchantform/',
)
JAZZCASH_PRODUCTION_PAYMENT_POST_URL = config(
    'JAZZCASH_PRODUCTION_PAYMENT_POST_URL',
    default='https://payments.jazzcash.com.pk/CustomerPortal/transactionmanagement/merchantform/',
)

JAZZCASH_PAY_SIGNING_SALT = config('JAZZCASH_PAY_SIGNING_SALT', default='medtag-jazzcash-pay')
try:
    JAZZCASH_PAY_LINK_MAX_AGE_SECONDS = int(config('JAZZCASH_PAY_LINK_MAX_AGE_SECONDS', default='3600'))
except ValueError:
    JAZZCASH_PAY_LINK_MAX_AGE_SECONDS = 3600

JAZZCASH_RESULT_FRONTEND_URL = config(
    'JAZZCASH_RESULT_FRONTEND_URL',
    default='',
)

# Email Settings - All from environment variables
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = int(config('EMAIL_PORT', default='587'))
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default='True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# OTP Settings
OTP_EXPIRY_MINUTES = 10

REACTAPP_RESET_URL = config('REACTAPP_RESET_URL')
LOGIN_URI = config('LOGIN_URI')

# ============================================================================
# SECURITY SETTINGS FOR PRODUCTION
# ============================================================================

if IS_PRODUCTION:
    # HTTPS and Security Headers
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Strict Transport Security (for HTTPS)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Referrer Policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ============================================================================
# LOGGING CONFIGURATION FOR PRODUCTION
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
            'propagate': False,
        },
    },
}