# Generated by Django 4.2.19 on 2025-12-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appointment_patient_medicalreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='MedicalReport',
        ),
    ]
