# Generated by Django 4.2.19 on 2025-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_doctor_experience_years_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
