# Generated by Django 6.0.4 on 2026-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_chatmessage_attachment_alter_chatmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
