# Generated by Django 6.0.4 on 2026-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_doctor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
