# Generated by Django 6.0.4 on 2026-05-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_withdrawal_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_email', models.EmailField(max_length=254)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_method', to='accounts.doctor')),
            ],
        ),
    ]
