# Generated by Django 6.0.4 on 2026-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_doctorpayoutmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpayoutmethod',
            name='stripe_account_email',
        ),
        migrations.AddField(
            model_name='doctorpayoutmethod',
            name='charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorpayoutmethod',
            name='details_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
