# Generated by Django 4.2.19 on 2025-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
